spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gominlog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8081

file:
  upload-dir: /home/ss/uploads